### ISSUE TITLE
Add plugins

### ISSUE THREAD

**Issue by 32leaves** [32leaves/werft#18]
Plugins are processes that are started by werft. They're passed a single argument pointing to a socket where a gRPC server listens on. The gRPC interface differs based on the plugin type.

Different plugin types are:
- _integration_ plugins work with the `https://github.com/32leaves/werft/tree/master/pkg/api/v1/werft.proto` API. This kind of plugins adds new means of feedback or for triggering builds based on external events. The GitHub integration is a candidate.
- _gitauth_ plugins provide Git authentication similar to Git credential helpers. Their API does not exist yet.

Other types that might follow: "log store", "job store"

Plugins are configured in the main config file:
```YAML
plugins:
  integration:
  - name: github
    command:
    - werft-github-integration
    - github-config.yaml
  - name: slack
    command: ["werft-slack-integration", "slack-config.yaml"]
  gitauth:
  - name: github
    command:
    - werft-github-gitauth
    - github-config.yaml
```
